server:
  port: 8888

logging:
  level:
    org:
      springframework:
        boot:
          # 오류만 출력
          autoconfigure: ERROR

upbit:
  accessKey:
  secretKey:

bithumb:
  apiKey:
  apiSecret: